### ISSUE TITLE
FileNotFoundException on Bullseye

### ISSUE THREAD

**Issue by TGlev** [linusg/rpi-backlight#47] opened 2022-05-30 13:43 UTC
Hi,

I made a new SD based on Bullseye today and after finally getting it to boot with the touch screen, I am now running into backlight issues because the /sys/class/backlight/rpi_backlight folder does not exist. Apart from this, the screen, including touch, works perfectly normal. 

Full trace:
```
pi@retinapi:~ $ rpi-backlight -b 100
Traceback (most recent call last):
  File "/home/pi/.local/bin/rpi-backlight", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/rpi_backlight/cli.py", line 78, in main
    backlight = Backlight(
  File "/home/pi/.local/lib/python3.9/site-packages/rpi_backlight/__init__.py", line 75, in __init__
    self._max_brightness = self._get_value("max_brightness")  # 255
  File "/home/pi/.local/lib/python3.9/site-packages/rpi_backlight/__init__.py", line 92, in _get_value
    raise e
  File "/home/pi/.local/lib/python3.9/site-packages/rpi_backlight/__init__.py", line 84, in _get_value
    return int((self._backlight_sysfs_path / name).read_text())
  File "/usr/lib/python3.9/pathlib.py", line 1255, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/backlight/rpi_backlight/max_brightness'
```

**Comment by linusg** [comment] 2022-05-30 14:15
Duplicate of #45. You can provide a custom path as shown in that issue. If this is Raspberry Pi OS and not plain Debian I'd be happy to incorporate a change to set the default path conditionally - PRs welcome.

**Closed by linusg** 2022-05-30 14:15 UTC

**Comment by TGlev** [comment] 2022-05-30 14:16
This is raspbian.
